micronaut:
  application:
    name: christmas-tree-animation-fireworks-${STAGE:debug}
    instance:
      id: ${random.shortuuid}
consul:
  client:
    registration:
      enabled: ${CONSUL_ENABLED:true}
      tags:
      - christmas-tree
      - animation
      - special
      - fireworks
      - ${STAGE:debug}
      retry-count: 5
      fail-fast: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
tracing:
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    http:
      url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}
      sampler:
        probability: ${ZIPKIN_PROBABILITY:1}
endpoints:
  all:
    sensitive: false
christmas:
  tree:
    strips: ${LED_STRIPS:16}
    leds-per-strip: ${LEDS_PER_STRIP:20}